import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@widgets/Header";
import { AuthProvider } from "@/src/app/providers/AuthProvider";
import { getCurrentUser, getEnrolledCourses } from "@/src/entities/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 서버에서 쿠키를 읽어 초기 유저 상태 생성
  const cookieStore = await cookies();
  const token = cookieStore.get("auth_token")?.value;

  let initialUser = null;
  let initialEnrolledCourses = [];

  if (token) {
    try {
      initialUser = await getCurrentUser(token);
      initialEnrolledCourses = await getEnrolledCourses(initialUser.id, token);
    } catch (error) {
      console.error("Failed to fetch initial user data:", error);
      // 토큰이 만료되었거나 유효하지 않은 경우
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full min-h-dvh`}
      >
        <AuthProvider
          initialUser={initialUser}
          initialEnrolledCourses={initialEnrolledCourses}
        >
          <Header showSearch={true} />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
